export enum FormFieldType {
  TEXT = 'text',
  EMAIL = 'email',
  PASSWORD = 'password',
  SEARCH = 'search',
  RADIO = 'radio',
  CHECKBOX = 'checkbox',
  NUMBER = 'number',
  RANGE = 'range',
  SELECT = 'select',
  CHIPS = 'chips',
  THEME = 'theme',
  TEXTAREA = 'textarea',
  CODE = 'code',
  BUSINESS_DATE = 'business-date',
  BUSINESS_TIME = 'business-time',
  INSTANT_DATE_TIME = 'instant-date-time',
}
