import { inject } from '@angular/core';
import { provideHttpClient } from '@angular/common/http';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import { MAT_ICON_DEFAULT_OPTIONS } from '@angular/material/icon';
import type { Decorator, Preview } from '@storybook/angular';
import { applicationConfig, componentWrapperDecorator } from '@storybook/angular';
import { setCompodocJson } from '@storybook/addon-docs/angular';
import { provideCharts, withDefaultRegisterables } from 'ng2-charts';
import { API_ORIGIN } from '@wiltech-labs/ngx-api-client';
import { TranslationsService, provideTranslations } from '@wiltech-labs/ngx-translations';
import { NGX_DATES_LOCALE } from '@wiltech-labs/ngx-dates';
import { NGX_FORMS_LOCALE } from '@wiltech-labs/ngx-forms';
import { NGX_CALENDAR_LOCALE } from '@wiltech-labs/ngx-calendar';
import { LocaleSync } from '../src/support/locale-sync';
import en from '../src/translations/en-GB.json';
import el from '../src/translations/el-GR.json';
// @ts-ignore -- generated by Compodoc on every `storybook` / `build-storybook` run (gitignored).
import docJson from '../documentation.json';

setCompodocJson(docJson);

/** Every locale resolver reads the one `TranslationsService`, so the `locale` toolbar drives them all. */
const followTranslationsLocale = () => {
  const translations = inject(TranslationsService);
  return () => translations.locale();
};

/** `theme` toolbar: forces `color-scheme` on <html>. The M3 theme resolves every token through
 *  `light-dark()`, so this alone flips the whole page. "system" falls back to the OS preference. */
const withColorScheme: Decorator = (story, context) => {
  const scheme = context.globals['theme'] as string | undefined;
  document.documentElement.style.colorScheme =
    scheme === 'light' || scheme === 'dark' ? scheme : '';
  return story();
};

const preview: Preview = {
  decorators: [
    applicationConfig({
      providers: [
        provideHttpClient(),
        provideAnimationsAsync(),
        // Every <mat-icon> is a Material Symbols Outlined glyph (font loaded in preview-head.html).
        { provide: MAT_ICON_DEFAULT_OPTIONS, useValue: { fontSet: 'material-symbols-outlined' } },
        provideCharts(withDefaultRegisterables()),
        // Fake origin — stories never reach a real API (see docs/Storybook.md "Deployment").
        { provide: API_ORIGIN, useValue: 'https://api.storybook.invalid' },
        provideTranslations({
          locales: ['en-GB', 'el-GR'],
          defaultLocale: 'en-GB',
          dictionaries: { 'en-GB': en, 'el-GR': el },
        }),
        { provide: NGX_DATES_LOCALE, useFactory: followTranslationsLocale },
        { provide: NGX_FORMS_LOCALE, useFactory: followTranslationsLocale },
        { provide: NGX_CALENDAR_LOCALE, useFactory: followTranslationsLocale },
      ],
    }),
    componentWrapperDecorator(LocaleSync, ({ globals }) => ({
      locale: globals['locale'] ?? 'en-GB',
    })),
    withColorScheme,
  ],
  globalTypes: {
    theme: {
      description: 'Colour scheme for every story',
      toolbar: {
        title: 'Theme',
        icon: 'contrast',
        items: [
          { value: 'system', title: 'System' },
          { value: 'light', title: 'Light', icon: 'sun' },
          { value: 'dark', title: 'Dark', icon: 'moon' },
        ],
        dynamicTitle: true,
      },
    },
    locale: {
      description: 'Locale for translations, dates, forms and the calendar',
      toolbar: {
        title: 'Locale',
        icon: 'globe',
        items: [
          { value: 'en-GB', title: 'English (UK)' },
          { value: 'el-GR', title: 'Ελληνικά' },
        ],
        dynamicTitle: true,
      },
    },
  },
  initialGlobals: { theme: 'system', locale: 'en-GB' },
  parameters: {
    layout: 'padded',
    controls: { expanded: true, sort: 'requiredFirst' },
    options: {
      storySort: {
        order: [
          'Introduction',
          'ngx-components',
          'ngx-ai-tools',
          'ngx-media',
          'ngx-graphs',
          'ngx-forms',
          'ngx-modals',
          'ngx-notifications',
          'ngx-translations',
          'ngx-dates',
          'ngx-calendar',
          'ngx-organization',
          'ngx-region-settings',
          'ngx-web-sockets',
          'ngx-api-client',
          'ngx-auth',
          'ngx-styles',
        ],
      },
    },
    a11y: { test: 'todo' },
  },
  tags: ['autodocs'],
};

export default preview;
